import { SeedItem } from './seedWardrobe';

export interface ExtendedAttributes {
  pattern?: string;
  style?: string;
  fabric?: string;
  sleeveLength?: string;
  neckline?: string;
  fit?: string;
  features?: string[];
  genderCategory?: 'male' | 'female' | 'unisex';
  subcategory?: string;
}

export type ComprehensiveWardrobeItem = SeedItem & ExtendedAttributes;

export const COMPREHENSIVE_CLOTHING_DATASET: ComprehensiveWardrobeItem[] = [
  // Blazers
  {
    category: 'outerwear',
    subcategory: 'blazer',
    image: require('../assets/images/blazers/blazer1.png'),
    brand: 'StyleAssistant',
    notes: 'Classic Navy Blazer',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#000080',
    pattern: 'Solid',
    style: 'Formal',
    fabric: 'Wool Blend',
    sleeveLength: 'Long Sleeve',
    neckline: 'Lapel',
    fit: 'Tailored',
    features: ['Gold buttons', 'Double vent'],
    genderCategory: 'unisex'
  },
  {
    category: 'outerwear',
    subcategory: 'blazer',
    image: require('../assets/images/blazers/blazer2.png'),
    brand: 'StyleAssistant',
    notes: 'Textured Grey Blazer',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#808080',
    pattern: 'Textured',
    style: 'Smart Casual',
    fabric: 'Tweed',
    sleeveLength: 'Long Sleeve',
    neckline: 'Lapel',
    fit: 'Regular',
    features: ['Patch pockets'],
    genderCategory: 'male'
  },
  {
    category: 'outerwear',
    subcategory: 'blazer',
    image: require('../assets/images/blazers/blazer3.png'),
    brand: 'StyleAssistant',
    notes: 'Black Tuxedo Blazer',
    tag: 'keep',
    favourite: true,
    hidden: false,
    colour: '#000000',
    pattern: 'Solid',
    style: 'Formal',
    fabric: 'Velvet',
    sleeveLength: 'Long Sleeve',
    neckline: 'Shawl Collar',
    fit: 'Slim',
    features: ['Satin lapels'],
    genderCategory: 'unisex'
  },
  {
    category: 'outerwear',
    subcategory: 'blazer',
    image: require('../assets/images/blazers/blazer4.png'),
    brand: 'StyleAssistant',
    notes: 'Beige Linen Blazer',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#F5F5DC',
    pattern: 'Solid',
    style: 'Casual',
    fabric: 'Linen',
    sleeveLength: 'Long Sleeve',
    neckline: 'Notch Lapel',
    fit: 'Relaxed',
    features: ['Breathable', 'Unlined'],
    genderCategory: 'unisex'
  },
  {
    category: 'outerwear',
    subcategory: 'blazer',
    image: require('../assets/images/blazers/blazer5.png'),
    brand: 'StyleAssistant',
    notes: 'Checkered Brown Blazer',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#8B4513',
    pattern: 'Check',
    style: 'Vintage',
    fabric: 'Wool',
    sleeveLength: 'Long Sleeve',
    neckline: 'Lapel',
    fit: 'Regular',
    features: ['Elbow patches'],
    genderCategory: 'male'
  },
  {
    category: 'outerwear',
    subcategory: 'blazer',
    image: require('../assets/images/blazers/blazer6.png'),
    brand: 'StyleAssistant',
    notes: 'White Summer Blazer',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#FFFFFF',
    pattern: 'Solid',
    style: 'Chic',
    fabric: 'Cotton Blend',
    sleeveLength: 'Long Sleeve',
    neckline: 'Lapel',
    fit: 'Tailored',
    features: ['Single button'],
    genderCategory: 'female'
  },
  {
    category: 'outerwear',
    subcategory: 'blazer',
    image: require('../assets/images/blazers/blazer7.png'),
    brand: 'StyleAssistant',
    notes: 'Pinstripe Office Blazer',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#2F4F4F',
    pattern: 'Pinstripe',
    style: 'Corporate',
    fabric: 'Polyester Blend',
    sleeveLength: 'Long Sleeve',
    neckline: 'Lapel',
    fit: 'Structured',
    features: ['Shoulder pads'],
    genderCategory: 'female'
  },
  {
    category: 'outerwear',
    subcategory: 'blazer',
    image: require('../assets/images/blazers/blazer8.png'),
    brand: 'StyleAssistant',
    notes: 'Red Statement Blazer',
    tag: 'keep',
    favourite: true,
    hidden: false,
    colour: '#FF0000',
    pattern: 'Solid',
    style: 'Bold',
    fabric: 'Crepe',
    sleeveLength: 'Long Sleeve',
    neckline: 'Lapel',
    fit: 'Oversized',
    features: ['Double breasted'],
    genderCategory: 'female'
  },
  {
    category: 'outerwear',
    subcategory: 'blazer',
    image: require('../assets/images/blazers/blazer9.png'),
    brand: 'StyleAssistant',
    notes: 'Camel Wool Blazer',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#C19A6B',
    pattern: 'Solid',
    style: 'Classic',
    fabric: 'Camel Hair',
    sleeveLength: 'Long Sleeve',
    neckline: 'Lapel',
    fit: 'Regular',
    features: ['Soft texture'],
    genderCategory: 'unisex'
  },
  {
    category: 'outerwear',
    subcategory: 'blazer',
    image: require('../assets/images/blazers/blazer10.png'),
    brand: 'StyleAssistant',
    notes: 'Blue Fitted Blazer',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#4169E1',
    pattern: 'Solid',
    style: 'Modern',
    fabric: 'Synthetic',
    sleeveLength: 'Long Sleeve',
    neckline: 'Lapel',
    fit: 'Slim',
    features: ['Stretch lining'],
    genderCategory: 'female'
  },

  // Hoodies
  {
    category: 'tops',
    subcategory: 'hoodie',
    image: require('../assets/images/hoodies/hoodie1.png'),
    brand: 'StreetWear',
    notes: 'Essential Grey Hoodie',
    tag: 'keep',
    favourite: true,
    hidden: false,
    colour: '#808080',
    pattern: 'Solid',
    style: 'Casual',
    fabric: 'Cotton Fleece',
    sleeveLength: 'Long Sleeve',
    neckline: 'Hooded',
    fit: 'Relaxed',
    features: ['Kangaroo pocket'],
    genderCategory: 'unisex'
  },
  {
    category: 'tops',
    subcategory: 'hoodie',
    image: require('../assets/images/hoodies/hoodie2.png'),
    brand: 'StreetWear',
    notes: 'Black Graphic Hoodie',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#000000',
    pattern: 'Graphic',
    style: 'Street',
    fabric: 'Cotton',
    sleeveLength: 'Long Sleeve',
    neckline: 'Hooded',
    fit: 'Oversized',
    features: ['Back print'],
    genderCategory: 'unisex'
  },
  {
    category: 'tops',
    subcategory: 'hoodie',
    image: require('../assets/images/hoodies/hoodie3.png'),
    brand: 'StreetWear',
    notes: 'Navy Zip-Up Hoodie',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#000080',
    pattern: 'Solid',
    style: 'Sporty',
    fabric: 'Polyester Blend',
    sleeveLength: 'Long Sleeve',
    neckline: 'Hooded',
    fit: 'Regular',
    features: ['Zipper closure'],
    genderCategory: 'unisex'
  },
  {
    category: 'tops',
    subcategory: 'hoodie',
    image: require('../assets/images/hoodies/hoodie4-1.png'),
    brand: 'StreetWear',
    notes: 'Beige Oversized Hoodie',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#F5F5DC',
    pattern: 'Solid',
    style: 'Minimalist',
    fabric: 'Heavyweight Cotton',
    sleeveLength: 'Long Sleeve',
    neckline: 'Hooded',
    fit: 'Oversized',
    features: ['Drop shoulder'],
    genderCategory: 'unisex'
  },
  {
    category: 'tops',
    subcategory: 'hoodie',
    image: require('../assets/images/hoodies/hoodie5-1.png'),
    brand: 'StreetWear',
    notes: 'Red Crop Hoodie',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#FF0000',
    pattern: 'Solid',
    style: 'Trendy',
    fabric: 'Cotton',
    sleeveLength: 'Long Sleeve',
    neckline: 'Hooded',
    fit: 'Cropped',
    features: ['Raw hem'],
    genderCategory: 'female'
  },
  {
    category: 'tops',
    subcategory: 'hoodie',
    image: require('../assets/images/hoodies/hoodie6.png'),
    brand: 'StreetWear',
    notes: 'Green Tech Hoodie',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#008000',
    pattern: 'Solid',
    style: 'Techwear',
    fabric: 'Nylon Blend',
    sleeveLength: 'Long Sleeve',
    neckline: 'Hooded',
    fit: 'Athletic',
    features: ['Water resistant'],
    genderCategory: 'male'
  },
  {
    category: 'tops',
    subcategory: 'hoodie',
    image: require('../assets/images/hoodies/hoodie8.png'),
    brand: 'StreetWear',
    notes: 'Tie-Dye Hoodie',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#ADD8E6',
    pattern: 'Tie-Dye',
    style: 'Boho',
    fabric: 'Cotton',
    sleeveLength: 'Long Sleeve',
    neckline: 'Hooded',
    fit: 'Relaxed',
    features: ['Unique wash'],
    genderCategory: 'unisex'
  },
  {
    category: 'tops',
    subcategory: 'hoodie',
    image: require('../assets/images/hoodies/hoodie9.png'),
    brand: 'StreetWear',
    notes: 'White Logo Hoodie',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#FFFFFF',
    pattern: 'Logo',
    style: 'Casual',
    fabric: 'Cotton',
    sleeveLength: 'Long Sleeve',
    neckline: 'Hooded',
    fit: 'Regular',
    features: ['Embroidered logo'],
    genderCategory: 'unisex'
  },

  // Jeans
  {
    category: 'bottoms',
    subcategory: 'jeans',
    image: require('../assets/images/jeans/jeans1.png'),
    brand: 'DenimCo',
    notes: 'Classic Straight Leg Jeans',
    tag: 'keep',
    favourite: true,
    hidden: false,
    colour: '#000080',
    pattern: 'Solid',
    style: 'Classic',
    fabric: 'Denim',
    sleeveLength: 'N/A',
    neckline: 'N/A',
    fit: 'Straight',
    features: ['5-pocket styling'],
    genderCategory: 'unisex'
  },
  {
    category: 'bottoms',
    subcategory: 'jeans',
    image: require('../assets/images/jeans/jeans2.png'),
    brand: 'DenimCo',
    notes: 'Skinny Black Jeans',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#000000',
    pattern: 'Solid',
    style: 'Modern',
    fabric: 'Stretch Denim',
    sleeveLength: 'N/A',
    neckline: 'N/A',
    fit: 'Skinny',
    features: ['High stretch'],
    genderCategory: 'female'
  },
  {
    category: 'bottoms',
    subcategory: 'jeans',
    image: require('../assets/images/jeans/jeans3.png'),
    brand: 'DenimCo',
    notes: 'Ripped Boyfriend Jeans',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#87CEEB',
    pattern: 'Distressed',
    style: 'Casual',
    fabric: 'Cotton Denim',
    sleeveLength: 'N/A',
    neckline: 'N/A',
    fit: 'Relaxed',
    features: ['Distressed details'],
    genderCategory: 'female'
  },
  {
    category: 'bottoms',
    subcategory: 'jeans',
    image: require('../assets/images/jeans/jeans4.png'),
    brand: 'DenimCo',
    notes: 'Slim Fit Dark Wash',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#191970',
    pattern: 'Solid',
    style: 'Smart Casual',
    fabric: 'Denim',
    sleeveLength: 'N/A',
    neckline: 'N/A',
    fit: 'Slim',
    features: ['Contrast stitching'],
    genderCategory: 'male'
  },
  {
    category: 'bottoms',
    subcategory: 'jeans',
    image: require('../assets/images/jeans/jeans5.png'),
    brand: 'DenimCo',
    notes: 'White Jeans',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#FFFFFF',
    pattern: 'Solid',
    style: 'Summer',
    fabric: 'Denim',
    sleeveLength: 'N/A',
    neckline: 'N/A',
    fit: 'Straight',
    features: ['Clean hem'],
    genderCategory: 'unisex'
  },
  {
    category: 'bottoms',
    subcategory: 'jeans',
    image: require('../assets/images/jeans/jeans6.png'),
    brand: 'DenimCo',
    notes: 'High-Waisted Mom Jeans',
    tag: 'keep',
    favourite: true,
    hidden: false,
    colour: '#4682B4',
    pattern: 'Solid',
    style: 'Vintage',
    fabric: 'Rigid Denim',
    sleeveLength: 'N/A',
    neckline: 'N/A',
    fit: 'Relaxed',
    features: ['Tapered leg'],
    genderCategory: 'female'
  },
  {
    category: 'bottoms',
    subcategory: 'jeans',
    image: require('../assets/images/jeans/jeans7.png'),
    brand: 'DenimCo',
    notes: 'Grey Faded Jeans',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#808080',
    pattern: 'Faded',
    style: 'Edgy',
    fabric: 'Denim',
    sleeveLength: 'N/A',
    neckline: 'N/A',
    fit: 'Skinny',
    features: ['Zip fly'],
    genderCategory: 'unisex'
  },
  {
    category: 'bottoms',
    subcategory: 'jeans',
    image: require('../assets/images/jeans/jeans8.png'),
    brand: 'DenimCo',
    notes: 'Bootcut Jeans',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#0000CD',
    pattern: 'Solid',
    style: 'Retro',
    fabric: 'Stretch Denim',
    sleeveLength: 'N/A',
    neckline: 'N/A',
    fit: 'Bootcut',
    features: ['Flared hem'],
    genderCategory: 'female'
  },
  {
    category: 'bottoms',
    subcategory: 'jeans',
    image: require('../assets/images/jeans/jeans9.png'),
    brand: 'DenimCo',
    notes: 'Carpenter Jeans',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#DEB887',
    pattern: 'Solid',
    style: 'Workwear',
    fabric: 'Canvas Denim',
    sleeveLength: 'N/A',
    neckline: 'N/A',
    fit: 'Loose',
    features: ['Utility loops'],
    genderCategory: 'male'
  },

  // T-Shirts
  {
    category: 'tops',
    subcategory: 't-shirt',
    image: require('../assets/images/t-shirts/t-shirt1.png'),
    brand: 'Basics',
    notes: 'Classic White Tee',
    tag: 'keep',
    favourite: true,
    hidden: false,
    colour: '#FFFFFF',
    pattern: 'Solid',
    style: 'Essential',
    fabric: 'Cotton',
    sleeveLength: 'Short Sleeve',
    neckline: 'Crew Neck',
    fit: 'Regular',
    features: ['Soft touch'],
    genderCategory: 'unisex'
  },
  {
    category: 'tops',
    subcategory: 't-shirt',
    image: require('../assets/images/t-shirts/t-shirt2.png'),
    brand: 'Basics',
    notes: 'Black V-Neck',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#000000',
    pattern: 'Solid',
    style: 'Casual',
    fabric: 'Cotton Blend',
    sleeveLength: 'Short Sleeve',
    neckline: 'V-Neck',
    fit: 'Slim',
    features: ['Ribbed collar'],
    genderCategory: 'unisex'
  },
  {
    category: 'tops',
    subcategory: 't-shirt',
    image: require('../assets/images/t-shirts/t-shirt3.png'),
    brand: 'Basics',
    notes: 'Grey Pocket Tee',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#808080',
    pattern: 'Solid',
    style: 'Casual',
    fabric: 'Jersey',
    sleeveLength: 'Short Sleeve',
    neckline: 'Crew Neck',
    fit: 'Regular',
    features: ['Chest pocket'],
    genderCategory: 'male'
  },
  {
    category: 'tops',
    subcategory: 't-shirt',
    image: require('../assets/images/t-shirts/t-shirt4.png'),
    brand: 'Basics',
    notes: 'Striped Sailor Tee',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#000080',
    pattern: 'Striped',
    style: 'Nautical',
    fabric: 'Cotton',
    sleeveLength: 'Short Sleeve',
    neckline: 'Boat Neck',
    fit: 'Relaxed',
    features: ['Side slits'],
    genderCategory: 'female'
  },
  {
    category: 'tops',
    subcategory: 't-shirt',
    image: require('../assets/images/t-shirts/t-shirt5.png'),
    brand: 'Basics',
    notes: 'Graphic Band Tee',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#2F4F4F',
    pattern: 'Graphic',
    style: 'Edgy',
    fabric: 'Vintage Cotton',
    sleeveLength: 'Short Sleeve',
    neckline: 'Crew Neck',
    fit: 'Oversized',
    features: ['Distressed print'],
    genderCategory: 'unisex'
  },
  {
    category: 'tops',
    subcategory: 't-shirt',
    image: require('../assets/images/t-shirts/t-shirt6.png'),
    brand: 'Basics',
    notes: 'Pastel Pink Tee',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#FFB6C1',
    pattern: 'Solid',
    style: 'Soft',
    fabric: 'Modal',
    sleeveLength: 'Short Sleeve',
    neckline: 'Scoop Neck',
    fit: 'Loose',
    features: ['Drapey fabric'],
    genderCategory: 'female'
  },
  {
    category: 'tops',
    subcategory: 't-shirt',
    image: require('../assets/images/t-shirts/t-shirt7.png'),
    brand: 'Basics',
    notes: 'Navy Muscle Tee',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#000080',
    pattern: 'Solid',
    style: 'Sporty',
    fabric: 'Performance Blend',
    sleeveLength: 'Sleeveless',
    neckline: 'Crew Neck',
    fit: 'Athletic',
    features: ['Moisture wicking'],
    genderCategory: 'male'
  },
  {
    category: 'tops',
    subcategory: 't-shirt',
    image: require('../assets/images/t-shirts/t-shirt8.png'),
    brand: 'Basics',
    notes: 'Yellow Cropped Tee',
    tag: 'keep',
    favourite: false,
    hidden: false,
    colour: '#FFFF00',
    pattern: 'Solid',
    style: 'Summer',
    fabric: 'Cotton',
    sleeveLength: 'Short Sleeve',
    neckline: 'Crew Neck',
    fit: 'Cropped',
    features: ['Boxy fit'],
    genderCategory: 'female'
  }
];
