export const HAIR_COLORS = [
  { id: '1', name: 'Black', image: require('../assets/images/hair_color_samples/color_01.jpg') },
  { id: '1B', name: 'Soft Black', image: require('../assets/images/hair_color_samples/color_02.jpg') },
  { id: '2', name: 'Dark Brown', image: require('../assets/images/hair_color_samples/color_03.jpg') },
  { id: '4', name: 'Medium Brown', image: require('../assets/images/hair_color_samples/color_04.jpg') },
  { id: '5', name: 'Med Light Brown', image: require('../assets/images/hair_color_samples/color_05.jpg') },
  { id: '6', name: 'Light Brown', image: require('../assets/images/hair_color_samples/color_06.jpg') },
  { id: '8', name: 'Golden Brown', image: require('../assets/images/hair_color_samples/color_07.jpg') },
  { id: '12', name: 'Dark Blonde', image: require('../assets/images/hair_color_samples/color_08.jpg') },
  { id: '14', name: 'Ash Blonde', image: require('../assets/images/hair_color_samples/color_09.jpg') },
  { id: '16', name: 'Blonde', image: require('../assets/images/hair_color_samples/color_10.jpg') },
  { id: '18', name: 'Medium Brown (18)', image: require('../assets/images/hair_color_samples/color_11.jpg') },
  { id: '22', name: 'Light Blonde', image: require('../assets/images/hair_color_samples/color_12.jpg') },
  { id: '24', name: 'Lt Golden Blonde', image: require('../assets/images/hair_color_samples/color_13.jpg') },
  { id: '30', name: 'Brownish Red', image: require('../assets/images/hair_color_samples/color_14.jpg') },
  { id: '33', name: 'Dark Red', image: require('../assets/images/hair_color_samples/color_15.jpg') },
  { id: 'M4/30', name: 'Med Brown Red Mix', image: require('../assets/images/hair_color_samples/color_16.jpg') },
  { id: 'M4/33', name: 'Med Brown Dark Red Mix', image: require('../assets/images/hair_color_samples/color_17.jpg') },
  { id: '60', name: 'Most Platinum', image: require('../assets/images/hair_color_samples/color_18.jpg') },
  { id: '613', name: 'Platinum', image: require('../assets/images/hair_color_samples/color_19.jpg') },
  { id: 'DB2', name: 'Neutral Blonde', image: require('../assets/images/hair_color_samples/color_20.jpg') },
  { id: '8/24', name: 'Golden Brown Duo', image: require('../assets/images/hair_color_samples/color_21.jpg') },
  { id: '18/22', name: 'Med Blonde Duo', image: require('../assets/images/hair_color_samples/color_22.jpg') },
  { id: '613/27', name: 'Platinum Honey Duo', image: require('../assets/images/hair_color_samples/color_23.jpg') },
  { id: '1B/4', name: 'Soft Black Duo', image: require('../assets/images/hair_color_samples/color_24.jpg') },
  { id: '66/46', name: 'Mahogany Red Mix', image: require('../assets/images/hair_color_samples/color_25.jpg') },
  { id: '99J', name: 'Dark Burgundy', image: require('../assets/images/hair_color_samples/color_26.jpg') },
  { id: 'Red', name: 'Red', image: require('../assets/images/hair_color_samples/color_27.jpg') },
  { id: 'Blue', name: 'Blue', image: require('../assets/images/hair_color_samples/color_28.jpg') },
  { id: 'Purple', name: 'Purple', image: require('../assets/images/hair_color_samples/color_29.jpg') },
  { id: 'Pink', name: 'Pink', image: require('../assets/images/hair_color_samples/color_30.jpg') },
  { id: 'Lilac', name: 'Lilac', image: require('../assets/images/hair_color_samples/color_31.jpg') },
  { id: 'Lt Pink', name: 'Light Pink', image: require('../assets/images/hair_color_samples/color_32.jpg') },
  { id: 'Sky', name: 'Sky', image: require('../assets/images/hair_color_samples/color_33.jpg') },
  { id: 'Silver', name: 'Silver', image: require('../assets/images/hair_color_samples/color_34.jpg') },
  { id: 'Teal', name: 'Teal', image: require('../assets/images/hair_color_samples/color_35.jpg') },
  { id: '8/24 Ombre', name: 'Gold Brown Ombre', image: require('../assets/images/hair_color_samples/color_36.jpg') },
  { id: '4/12 Ombre', name: 'Med Brown Ombre', image: require('../assets/images/hair_color_samples/color_37.jpg') },
];
